config/routes.rb
CheckAvailability::Application.routes.draw do
  resources :units
  resources :calendars

  get "home/index"
  put "home/refresh"

  root to: "home#index"

end

app/models/calendar.rb
class Calendar < ActiveRecord::Base

  REFRESH_INTERVAL = 3

  attr_accessible :dates, :refresh_date, :unit_id

  belongs_to :unit

  serialize :dates, Array

  after_validation :set_refresh_date

  def check_availability(arrival, depart, num_of_people)
    available = Integer(num_of_people) <= unit.capacity
    available && vrbo_calendar.available?(arrival, depart, dates)
  end

  def time_to_refresh?
    dates.empty? || (refresh_date.nil? || REFRESH_INTERVAL.hours.ago > refresh_date)
  end

  def refresh_available_dates!
    puts "-> getting #{unit.name}"
    update_attributes!(refresh_date: Time.now, dates: vrbo_calendar.find_available_dates)
    puts "-> got #{unit.name}"
  end

  def vrbo_calendar
    VRBO::Calendar.new(unit.calendar_url) # actually the url is just the unit now id
  end

  private

  def set_refresh_date
    self.refresh_date = Time.now
  end
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  attr_accessible :calendar_url, :name, :capacity

  has_one :calendar

  after_create :create_calendar
  after_update :create_calendar

  after_validation :set_default_capacity

  validates :name, :calendar_url, presence: true
  validates :name, uniqueness: {case_sensitive: false}
  validates :capacity, numericality: true

  class << self
    def refresh_all
      refresh(all.reject { |u| u.calendar.nil? }, true)
    end

    def find_openings(start_date, end_date, num_of_people)
      units = all.reject { |u| u.calendar.nil? }
      refresh(units)
      units.keep_if { |u| u.calendar.check_availability(start_date, end_date, num_of_people) }
    end

    def refresh(units, force=false)
      units.map { |u|
        Thread.new do
          if force || u.calendar.time_to_refresh?
            u.calendar.refresh_available_dates!
          end
        end
      }.each(&:join)
    end
  end

  def vrbo_url
    VRBO::Calendar.new(calendar_url).url
  end

  private

  def create_calendar
    calendar || create_calendar!
  end

  def set_default_capacity
    self.capacity ||= 2
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  # GET /calendars
  # GET /calendars.json
  def index
    @calendars = Calendar.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @calendars }
    end
  end

  # GET /calendars/1
  # GET /calendars/1.json
  def show
    @calendar = Calendar.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @calendar }
    end
  end

  # GET /calendars/new
  # GET /calendars/new.json
  def new
    @calendar = Calendar.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @calendar }
    end
  end

  # GET /calendars/1/edit
  def edit
    @calendar = Calendar.find(params[:id])
  end

  # POST /calendars
  # POST /calendars.json
  def create
    @calendar = Calendar.new(params[:calendar])

    respond_to do |format|
      if @calendar.save
        format.html { redirect_to @calendar, notice: 'Calendar was successfully created.' }
        format.json { render json: @calendar, status: :created, location: @calendar }
      else
        format.html { render action: "new" }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /calendars/1
  # PUT /calendars/1.json
  def update
    @calendar = Calendar.find(params[:id])

    respond_to do |format|
      if @calendar.update_attributes(params[:calendar])
        format.html { redirect_to @calendar, notice: 'Calendar was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calendars/1
  # DELETE /calendars/1.json
  def destroy
    @calendar = Calendar.find(params[:id])
    @calendar.destroy

    respond_to do |format|
      format.html { redirect_to calendars_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @range = DateRange.new(params[:start_date], params[:end_date])
    @calendar = Calendar.order('refresh_date DESC').first
    if params[:start_date]
      errors = []
      if @range.start_at > @range.stop_at
        errors << 'Departure date should be later than arrival date'
      elsif Time.zone.now.to_date > @range.start_at.to_date
        errors << 'You should really plan for a trip in the future instead of the past'
      end

      if errors.blank?
        @units = Unit.find_openings(@range.start_at, @range.stop_at, params[:number_of_people])
      else
        request.flash[:errors] = errors[0]
      end
    end
  end

  def refresh
    Unit.refresh_all
    redirect_to(home_index_path, notice: 'Calendars have been refreshed!')
  end

  class DateRange

    attr_accessor :start_at, :stop_at

    def initialize(star=nil, en=nil)
      @start_at = Date.parse(convert_date(star)) rescue Time.zone.now
      @stop_at = Date.parse(convert_date(en)) rescue 2.days.from_now
    end

    private

    def convert_date(the_date)
      the_date.gsub(%r{(\d{2})/(\d{2})/(\d+)}, '\3-\1-\2')
    end

  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  # GET /units
  # GET /units.json
  def index
    @units = Unit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @units }
    end
  end

  # GET /units/1
  # GET /units/1.json
  def show
    @unit = Unit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @unit }
    end
  end

  # GET /units/new
  # GET /units/new.json
  def new
    @unit = Unit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @unit }
    end
  end

  # GET /units/1/edit
  def edit
    @unit = Unit.find(params[:id])
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(params[:unit])

    respond_to do |format|
      if @unit.save
        format.html { redirect_to units_path, notice: 'Unit was successfully created.' }
        format.json { render json: @unit, status: :created, location: @unit }
      else
        format.html { render action: "new" }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /units/1
  # PUT /units/1.json
  def update
    @unit = Unit.find(params[:id])

    respond_to do |format|
      if @unit.update_attributes(params[:unit])
        format.html { redirect_to units_path, notice: "#{@unit.name} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit = Unit.find(params[:id])
    @unit.destroy

    respond_to do |format|
      format.html { redirect_to units_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/calendars/_form.html.erb
<%= form_for(@calendar) do |f| %>
  <% if @calendar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@calendar.errors.count, "error") %> prohibited this calendar from being saved:</h2>

      <ul>
      <% @calendar.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :unit_id %><br />
    <%= f.number_field :unit_id %>
  </div>
  <div class="field">
    <%= f.label :dates %><br />
    <%= f.text_field :dates %>
  </div>
  <div class="field">
    <%= f.label :refresh_date %><br />
    <%= f.datetime_select :refresh_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/calendars/edit.html.erb
<h1>Editing calendar</h1>

<%= render 'form' %>

<%= link_to 'Show', @calendar %> |
<%= link_to 'Back', calendars_path %>

app/views/calendars/index.html.erb
<h1>Listing calendars</h1>

<table>
  <tr>
    <th>Unit</th>
    <th>Dates</th>
    <th>Refresh date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @calendars.each do |calendar| %>
  <tr>
    <td><%= calendar.unit_id %></td>
    <td><%= calendar.dates %></td>
    <td><%= calendar.refresh_date %></td>
    <td><%= link_to 'Show', calendar %></td>
    <td><%= link_to 'Edit', edit_calendar_path(calendar) %></td>
    <td><%= link_to 'Destroy', calendar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Calendar', new_calendar_path %>

app/views/calendars/new.html.erb
<h1>New calendar</h1>

<%= render 'form' %>

<%= link_to 'Back', calendars_path %>

app/views/calendars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Unit:</b>
  <%= @calendar.unit_id %>
</p>

<p>
  <b>Dates:</b>
  <%= @calendar.dates %>
</p>

<p>
  <b>Refresh date:</b>
  <%= @calendar.refresh_date %>
</p>


<%= link_to 'Edit', edit_calendar_path(@calendar) %> |
<%= link_to 'Back', calendars_path %>

app/views/home/index.html.erb
<div style="float:right">
  <%= form_tag(home_refresh_path, method: :put) { submit_tag('Refresh calendars', class: 'btn btn-info', disable_with: 'Refreshing ...') } %>
</div>
<h2>Search</h2>
<div class="well">
  <%= form_tag({}, method: :get, id: 'search_dates') do %>
      <div class="clearfix">
        <div class="field">
          <%= label_tag(:start_date) %>
          <%= text_field_tag(:start_date, @range.start_at.strftime('%m/%d/%Y'), class: 'dp') %>
        </div>
        <div class="field">
          <%= label_tag(:end_date) %>
          <%= text_field_tag(:end_date, @range.stop_at.strftime('%m/%d/%Y'), class: 'dp') %>
        </div>
        <div class="field">
          <%= label_tag(:number_of_people) %>
          <%= number_field_tag(:number_of_people, params[:number_of_people] || 2, style: 'width: 30px;') %>
        </div>
      </div>
      <%= submit_tag('Search', class: 'btn btn-primary', name: nil, disable_with: 'Searching ...') %>
      <%= link_to('Clear', home_index_path, class: 'btn') %>
      <p style="margin: 3px 0;color: #666;">
        * Calendars automatically refresh every <%= Calendar::REFRESH_INTERVAL %> hours.
        <% if @calendar.try(:refresh_date) %>
            Last refreshed on
            <span style="color: #000;"><%= @calendar.refresh_date.strftime('%B %d, %Y %l:%M %p') %></span>
        <% end %>
      </p>
  <% end %>
  <% if @units %>
      <h3 style="margin-top: 5px;padding-top: 5px;border-top: 1px solid #CCC;">Openings</h3>

      <% if @units.any? %>
          <% @units.each do |unit| %>
              <%= link_to(unit.name, unit.vrbo_url, class: 'btn btn-large', target: '_blank') %>
          <% end %>
      <% else %>
          <h5>Nothing</h5>
      <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : 'Check Availability' %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag('application', media: 'all') %>
  <%= yield :header %>
</head>
<body>

<div class="navbar navbar-fluid-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <h1><a class="brand" href="/">Check Availability</a></h1>

      <div class="container-fluid">
        <ul class="nav">
          <li class="<%= 'active' if controller_name == 'home' %>">
            <%= link_to 'Search', home_index_path %>
          </li>
          <li class="<%= 'active' if controller_name == 'units' %>">
            <%= link_to 'Units', units_path %>
          </li>
        </ul>
      </div>
      <!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row-fluid content-wrap">
    <%= content_tag(:div, request.flash.discard.first[1], class: 'alert notice alert-notice') if request.flash.any? %>
    <%= yield %>
  </div>
</div>
<!-- /container -->
<%= javascript_include_tag "application" %>
</body>
</html>

app/views/units/_form.html.erb
<%= form_for(@unit) do |f| %>
    <% if @unit.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

          <ul>
            <% @unit.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="clearfix">
      <div class="field">
        <%= f.label :name %>
        <br/>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :capacity %>
        <br/>
        <%= f.number_field :capacity, style: 'width: 50px;' %>
      </div>
      <div class="field">
        <%= f.label :calendar_url, 'VRBO Unit #' %>
        <br/>
        <%= f.text_field :calendar_url, style: 'width: 450px;' %>
      </div>
    </div>
    <div class="actions">
      <%= f.submit('Save', class: 'btn btn-primary', disable_with: 'Saving ...') %>
      <%= link_to('Cancel', units_path, class: 'btn') %>
    </div>
<% end %>

app/views/units/edit.html.erb
<h2>Editing unit</h2>

<div class="well clearfix">
  <%= render 'form' %>
</div>

app/views/units/index.html.erb
<h1>Units</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Capacity</th>
    <th>VRBO Listing</th>
    <th></th>
    <th></th>
  </tr>

<% @units.each do |unit| %>
  <tr>
    <td><%= unit.name %></td>
    <td><%= unit.capacity %></td>
    <td><%= link_to(unit.vrbo_url, unit.vrbo_url, target: '_blank') %></td>
    <td><%= link_to 'Edit', edit_unit_path(unit), class: 'btn' %></td>
    <td><%= link_to 'Destroy', unit, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Unit', new_unit_path, class: 'btn btn-primary' %>

app/views/units/new.html.erb
<h2>New unit</h2>

<div class="well">
  <%= render 'form' %>
</div>

app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @unit.name %>
</p>

<p>
  <b>Calendar url:</b>
  <%= @unit.calendar_url %>
</p>


<%= link_to 'Edit', edit_unit_path(@unit) %> |
<%= link_to 'Back', units_path %>